### ISSUE TITLE
There are some problem in PyCA

### ISSUE THREAD

**Issue by ha-nso-li** [rkwitt/quicksilver#2]
Hello. I'm trying to run these codes, but I met some issue in PyCA.

```
(quicksilver) [hansoli@localhost applications]$ python qs_predict.py --moving-image ../CUMC_examples/m1.nii --target-image ../CUMC_examples/m2.nii --output-prefix /home/hansoli
Traceback (most recent call last):
  File "qs_predict.py", line 20, in <module>
    import PyCA.Core as ca
  File "/home/hansoli/anaconda3/envs/quicksilver/lib/python2.7/site-packages/PyCA/Core.py", line 28, in <module>
    _Core = swig_import_helper()
  File "/home/hansoli/anaconda3/envs/quicksilver/lib/python2.7/site-packages/PyCA/Core.py", line 24, in swig_import_helper
    _mod = imp.load_module('_Core', fp, pathname, description)
ImportError: /home/hansoli/quicksilver/3rd_party_software/pyca/Build/bin/libPyCA.so: undefined symbol: _ZN3itk27TransformFileReaderTemplateIdE16GetTransformListB5cxx11Ev
```

Anybody knows how to solve this? What version of package needed when compile PyCA?

I'm using machine with following environments:

Fedora 26
CUDA 8.0 (GTX 1050)
gcc 5.4 (for cuda), gcc 7.2 (for others)
swig 2.0.12 (i couldn't compile with latest 3.0.12)
InsightToolkit-devel 4.9.1
vxl-devel 1.17.0
fftw-devel 3.3.5
boost-devel 1.63.0
Python 2.7.13 (NumPy 1.13.1)

**Comment by seanbefore** [comment]
hi, i come across the same problem and have no idea with it. Have you solved it?

**Comment by seanbefore** [comment]
Hello the issue has been solved by changing the version of the PyCA, the PyCA here doesn't work now.[the updated source](https://bitbucket.org/scicompanat/pyca/src/master/)

**Comment by ha-nso-li** [comment]
Sorry for late response :'(

I couldn't solve this problem and I'm not paying attention to this code now.
I'll test your solution later.

**Comment by ha-nso-li** [comment]
Closing the issue that I'm not interested in anymore.
